force-app/main/default/objects/Account/fields/QualificacaoCliente__c.field-meta.xml
<CustomField>
    <fullName>QualificacaoCliente__c</fullName>
    <label>Qualificação do Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Ouro</fullName>
            </value>
            <value>
                <fullName>Prata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vendedor__c/Vendedor__c.object-meta.xml
<CustomObject>
    <label>Vendedor</label>
    <nameField>
        <label>Nome de Vendedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vendedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestAccountTrigger.cls
@isTest
public with sharing class TestAccountTrigger {
    @isTest
    public static void testInsertGoldAccount(){
        List<Account> accountsToInsert =  AccountDataFactory.createAccounts(1,'Ouro');

        List<Vendedor__c> vendedores = new List<Vendedor__c>();

        vendedores.addAll(VendedorDataFactory.criarVendedoresInternos(1));
        vendedores.addAll(VendedorDataFactory.criarVendedoresExternos(1));

        Test.startTest();
        insert vendedores;
        insert accountsToInsert;

        Account[] assertAccount = [SELECT Id,QualificacaoCliente__c FROM Account WHERE QualificacaoCliente__c = 'Ouro'];

        Test.stopTest();

        System.assertNotEquals(null, assertAccount[0].Vendedor__c,'Vendedor da Conta não foi atualizada');
        

    }

}