force-app/main/default/objects/Account/fields/QualificacaoCliente__c.field-meta.xml
<CustomField>
    <fullName>QualificacaoCliente__c</fullName>
    <label>Qualificação do Cliente</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bronze</fullName>
            </value>
            <value>
                <fullName>Ouro</fullName>
            </value>
            <value>
                <fullName>Prata</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AccountDataFactory.cls
public with sharing class AccountDataFactory {
    public static List<Account> createAccounts(Integer noOfAccountsToCreate, String qualification) {

        
        List<Account> accounts = new List<Account>();
        
        for(Integer i=0;i<noOfAccountsToCreate;i++){
            Account acc = new Account(Name = 'Test' + i,CEP__c = '13801035');
            acc.QualificacaoCliente__c = qualification;
            accounts.add(acc);
        }

        return accounts;

    }
}